### ISSUE TITLE
Parse documents with attached formatting:

### ISSUE THREAD

**Issue by ja-roque** [ja-roque/modulos-app#2]
[parsedDoc2.txt](https://github.com/ja-roque/modulos-app/files/1672572/parsedDoc2.txt)

Docs in this link: https://drive.google.com/open?id=1Xsuj2iOqGxkRN4VIJk-GUgJUywO5nRZ0

directory: modulos/(el modulo)/lectura.pdf.

(Final product should look like attached doc. parsing separating it is meant to be done in slides and slide fragments, each slide should be the size of a paragraph ( see the first slide in attached doc for new slide size reference.)

**Comment by roque510** [comment]
They are now parsed with extension .txt or if files were to extended they were made .pptx named LECTURE #
